run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - gofmt
    - goimports
  disable:
    - dupl
    - gocyclo
